# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you're deploying from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Git for Deployment
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    
    - name: Create config.js with API Key
      run: |
        echo "const OPENAI_API_KEY = '${{ secrets.OPENAI_KEY }}';" > config.js
      shell: bash

    - name: Verify config.js Created
      run: ls -la  # List files to ensure config.js was created

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory where index.html is located
        destination_branch: gh-pages  # Ensure it deploys to the gh-pages branch
        force_orphan: true  # Ensure a clean push to gh-pages
