# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or the branch you are deploying from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Update to latest version (v3 uses Node 16 and up)

    - name: Set up Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Create config.js with API Key
      run: |
        echo "const OPENAI_API_KEY = '${{ secrets.OPENAI_KEY }}';" > config.js
      shell: bash

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Update to latest version (v4 uses Node 16 and up)
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Assuming your index.html is at the root
        force_orphan: true  # Use an orphan commit to avoid branch conflicts
